apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-priv
  labels:
    app: nginx-priv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-priv
  template:
    metadata:
      labels:
        app: nginx-priv
    spec:
      containers:
      - name: nginx-priv
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]
