apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: my-psp
spec:
  privileged: false  # Prevents creation of privileged Pods
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAs
    ranges:
      - min: 2005
        max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1005
        max: 65535
  volumes:
  - '*'

